### ISSUE TITLE
Conflicts with OpenCV

### ISSUE THREAD

**Issue by mihaibujanca** [niessner/Opt#110]
Including `mLib/core-util/keycodes.h` in `examples/external/mLib/include/mLibCore.h` does not seem necessary for Opt and produces a conflict with OpenCV.
(please see https://github.com/mihaibujanca/dynamicfusion/issues/19#issuecomment-348734110, https://github.com/mihaibujanca/dynamicfusion/issues/33#issuecomment-349348562) due to conflicting macros.

Will create a similar issue in the main mLib repository but figured I'd also write here since you're not using it as a subrepository.

**Comment by Mx7f** [comment]
Thanks, I will try to fix soon.
