### ISSUE TITLE
Which license?

### ISSUE THREAD

**Issue by fabiencastan** [niessner/Opt#137]
Hi,

In the [presentation at Siggraph](https://cs.stanford.edu/people/mmara/Opt_SIGGRAPH2018.pdf) Opt was presented as released under MIT license.
But the [license in the repository](https://github.com/niessner/Opt/blob/master/LICENSE.txt) says:
"Opt is licensed under a Creative Commons Attribution-NonCommercial-ShareAlike 3.0 Unported License."

Which license applies?

Thanks for sharing this very interesting library!
Best,

**Comment by Mx7f** [comment]
Thanks for pointing this out; this was an oversight on our part. We've relicensed as MIT as of the latest commit (ba5e661). I'll make a new release version as well soon.

**Comment by fabiencastan** [comment]
Thanks!
