### ISSUE TITLE
Windows10 VS2013 make opt.lib error

### ISSUE THREAD

**Issue by HollisJoe** [niessner/Opt#61]
Cannot find the "stdio.h" file?What's the problem?Thank you for answering me.
![default](https://cloud.githubusercontent.com/assets/24452259/24029888/4e17afd8-0b14-11e7-9bbe-2e9e95fddba7.png)

**Comment by Mx7f** [comment]
Hmm, that sounds like a problem with the clang installation... does terra work on its own? Try going into D:\com-InteriorModeling\Projects\Optlang\terra\bin and running "terra", then "=3+4". You should get output like:

Terra -- A low-level counterpart to Lua

Stanford University
zdevito@stanford.edu

> =3+4
7

but my guess is you will get the same file not found problem. Can you confirm? You are using [the latest binary release of terra](https://github.com/zdevito/terra/releases/download/release-2016-03-25/terra-Windows-x86_64-332a506.zip), correct?

**Comment by HollisJoe** [comment]
I was using the latest binary release of terra, and I was get output like this:
![default](https://cloud.githubusercontent.com/assets/24452259/24086686/2f215efc-0d4f-11e7-96da-3eb55c61110a.png)
This is a problem windows10?

**Comment by HollisJoe** [comment]
I switch the computer on it

**Comment by Mx7f** [comment]
Is the new computer also Windows 10?

**Comment by HollisJoe** [comment]
Yes！I was copy  file terra and Opt to another win10 computer.

**Comment by HollisJoe** [comment]
But now I only use it a computer, all other computers cannot be successfully compiled, also rely on what compile environment?

**Comment by HollisJoe** [comment]
Hi! What kind of question is that?
![default](https://cloud.githubusercontent.com/assets/24452259/24396174/db6c60fe-13d4-11e7-9a0e-ed61782af693.png)
Thanks!

**Comment by Mx7f** [comment]
I haven't seen that before! Can you run the tests in terra and make sure they pass? The tests are in terra/share/terra/tests; and can be run with "terra run" in that directory.

**Comment by HollisJoe** [comment]
I compiled terra from scratch，and example compiles successfully, but some can be executed successfully, some not!
![default](https://cloud.githubusercontent.com/assets/24452259/24491403/a222625e-1559-11e7-8229-fa770785063f.png)
![default](https://cloud.githubusercontent.com/assets/24452259/24491471/01d95770-155a-11e7-8be1-aa3d26b06b1e.png)
embedded_mesh_deformation and robust_nonrigid_alignment are failed! Other successful! Do you know what the problem is?

**Comment by Mx7f** [comment]
I do not know what the problem is. Can you copy the error messages and stacktraces for both failures here?

**Comment by yhdegit** [comment]
Hello HollisJoe

     I have the same problem with you. Is there any other needed compile environment?

**Comment by joshuafc** [comment]
We found visual studio must install at C:\Program Files (x86)\Microsoft Visual Studio 12.0
solved

**Comment by rongduo** [comment]
I run the examples and I met the error as shown in the follow!
![1](https://user-images.githubusercontent.com/13198932/31605800-cde1b9ca-b299-11e7-93a1-307770a36ea3.png)
![2](https://user-images.githubusercontent.com/13198932/31605824-e9a86fbe-b299-11e7-981e-d6844b62ad08.jpg)

**Comment by HollisJoe** [comment]
The visual studio install at C:\Program Files (x86)\Microsoft Visual Studio**.*?
