### ISSUE TITLE
"optlang": Naming conflict

### ISSUE THREAD

**Issue by Masterxilo** [niessner/Opt#63]
Are you guys aware of the project

https://github.com/biosustain/optlang

with the same name?

**Comment by Mx7f** [comment]
Now we are, thanks for the heads-up!

**Comment by Masterxilo** [comment]
The other side thinks it's not an issue: https://github.com/biosustain/optlang/issues/103

> It seems that the purpose of that package is quite different from this one, so I don't think the name conflict will be an issue.

**Comment by Mx7f** [comment]
Great, thanks!
