### ISSUE TITLE
error in running example project in vs2013

### ISSUE THREAD

**Issue by cxqdssaw** [niessner/Opt#64]
I have an error when running any example project in vs2013, the error shows as follows:
![sfs01](https://cloud.githubusercontent.com/assets/25246615/25037906/63751ca0-212e-11e7-8d4c-9978b70f6dcf.JPG)
I use the [terra(terra-Windows-x86_64-2fa8d0a.zip)](https://github.com/zdevito/terra/releases). Is there something wrong with terra?

Any help will be appreciated.

**Comment by Mx7f** [comment]
Hmm, the compute_61 architecture is only supported only CUDA 8.0+. A potential workaround is to just install CUDA 8.0, but our documentation suggests you only need 7.5, so I will look into patching Opt to fix this.

**Comment by Mx7f** [comment]
Ah, you are also using an older version of terra, that might be it. Please use [then 3-25-2016 Release](https://github.com/zdevito/terra/releases/download/release-2016-03-25/terra-Windows-x86_64-332a506.zip) as required by Opt.

**Comment by cxqdssaw** [comment]
Thanks for yor comment. However, when I use CUDA 8.0 and the new terra 3-25-2016 Release instead and run the example: arap_mesh_deformation, I meet an error as [follows:](url
![default](https://cloud.githubusercontent.com/assets/25246615/25089377/a73dd5fc-23af-11e7-894e-a2b401666181.PNG)
)
So I trace the error and find the error occurs at 
`m_optimizerState = Opt_NewState(initParams);  // OptSolver.h line 48`

`addSolver(std::make_shared<OptSolver>(dims, problemFilename, "gaussNewtonGPU", doublePrecision), "Opt(GN)", true); //CombinedSolverBased.h line 75`

`addOptSolvers(m_dims, "arap_mesh_deformation.t", m_combinedSolverParameters.optDoublePrecision); //combinedSolver.h line 43`

`CombinedSolver solver(mesh, constraintsIdx, constraintsTarget, params, weightFit, weightReg); //main.h line 105`
To my surprise, it locates where I met the error as before(Look at the top). So I think it may be caused by Opt.h.

**Comment by Mx7f** [comment]
The error is that the terra compiler cannot find the cuda headers (cuda_runtime.h) when processing API/src/util.t, which suggests it doesn't have cuda in its include path. Can you try running the a cuda test (like terra\share\terra\tests\cudaatomic.t) and see if that works?

Clicking buildOpt.bat should probably work (I've only run it from cmd), so long as you followed the instructions:

"Our recommended directory structure for development is:

/Optlang/Opt (this repo)
/Optlang/terra (renamed from the fully qualified directory name from the release download)
If you change this repo structure, you must update Opt/API/buildOpt.bat's second argument on line 2 to point to the terra repo. If you compiled terra from scratch, its internal directory structure might also be different from the release, and you will need to update Opt/API/optMake.bat's line 3 to point to the terra binary."

so I don't think thats it.

**Comment by cxqdssaw** [comment]
Thanks. You are right. I could not run the cuda test(like terra\share\terra\tests\cudaatomic.t). 
![2](https://cloud.githubusercontent.com/assets/25246615/25129997/11fa6c98-2473-11e7-8655-d0c79ace9d26.PNG)
It seems that terralib..cudacompile is FALSE. How could I fix this? Do I need to compile terra source code instead of using the binary terra?

**Comment by Mx7f** [comment]
Apologies for the late response. I am not sure! That is certainly an option. You could also see if others have had similar problems at the [issue tracker for Terra](https://github.com/zdevito/terra) or it's [mailing list archives](https://mailman.stanford.edu/pipermail/terralang/).

**Comment by cxqdssaw** [comment]
I have switched to Ubuntu and everything is well now.  
Thanks anyway.
