### ISSUE TITLE
Solving problem through API - 'unknowns must be floating point numbers' assert violated

### ISSUE THREAD

**Issue by mvito** [niessner/Opt#65]
Hi,
I am trying to use Opt through the API and generate a simple example. I am trying to develop the Laplacian smoothness as is written in the paper. 

I created the file "laplacian.opt" as follows:

```W,H = Dim("W",0), Dim("H",1)
X = Unknown("X",float,{W,H},0)
A = Array("A",float,{W,H},1)
w_fit,w_reg = .1,.9
Energy(w_fit*(X(0,0) - A(0,0)), --fitting
w_reg*(X(0,0) - X(1,0)), --regularization
w_reg*(X(0,0) - X(0,1)))
```

Also, I have created a simple program to read an image, generate the program and solve it as follows:

```#pragma once
extern "C" {
#include "Opt.h"
}
#include <opencv2/core/core.hpp>
#include <opencv2/highgui/highgui.hpp>
#include <iostream>`

using namespace cv;
using namespace std;

void SolveLaplacian(int width, int height, float* unknown, float* target) {
    Opt_InitializationParameters param;
    param.doublePrecision = 1;
    param.verbosityLevel = 1;
    param.collectPerKernelTimingInfo = 1;
    Opt_State* state = Opt_NewState(param);
    // load the Opt DSL file containing the cost description
    Opt_Problem* problem = Opt_ProblemDefine(state,"../src/laplacian.opt", "solverGaussNewtonGPU");
    // describe the dimensions of the instance of the problem
    uint32_t dims[] = { width, height };
    Opt_Plan* plan = Opt_ProblemPlan(state, problem, dims);
    // run the solver
    void* problem_data[] = { unknown, target };
    Opt_ProblemSolve(state, plan, problem_data);
}


int main(){


  int width, height;
  float *unknown;
  float *target;
  Mat image, output;
  image = imread("../data/cat512.png");
  image.convertTo(image,CV_32F);

  /*namedWindow( "Display window", WINDOW_AUTOSIZE );// Create a window for display.
  imshow( "Display window", image );               // Show our image inside it.
  waitKey(10);  */                                   // Wait for a keystroke in the window

  width = image.cols;
  height = image.rows;
  output = Mat::ones(height,width,CV_32F);

  target = new float[width*height];
  unknown = new float[width*height];
  target = (float*)image.data;
  unknown = (float*)output.data;
  SolveLaplacian(width, height, unknown, target);

  return 0;

}
```

I am able to compile the project, but when I run it, I have this error:

```
o.t:629: unknowns must be floating point numbers
stack traceback:
	[C]: in function 'assert'
	o.t:629: in function 'fn'
	o.t:617: in function 'MapAndGroupBy'
	o.t:628: in function 'init'
	src/asdl.lua:319: in function 'UnknownType'
	o.t:260: in function 'UnknownType'
	o.t:1952: in function 'createjtjcentered'
	o.t:2355: in function 'problemSpecFromFile'
	o.t:825: in function <o.t:819>
	[C]: in function 'xpcall'
	o.t:819: in function <o.t:818>
0   terra (JIT)                         0x00007fbe7cdac00d $opt.ProblemSolve + 13 
./Refine(_Z14SolveLaplacianiiPfS_+0x7d) [0x69eb5d]
[0x3f8000003f800000]
Segmentation fault (core dumped)
```

Do you have any idea from where this error may come?
Thanks

**Comment by Mx7f** [comment]
Ah, I will improve that error message #72; you set Opt to use double-precision, but then use single-precision floats as Unknowns: the precision must match.

**Comment by ricshaw** [comment]
Hi, I am also having trouble with this. Using the above code and changing param.doublePrecision to 0, it compiles and attempts to solve it, but I get the following error:
Cuda reported error 11: invalid argument
In call: cudaCreateTextureObject(&tex, &res_desc, &tex_desc, [&cudaResourceViewDesc](nil))

**Comment by mvito** [comment]
When you define the problem:

`    Opt_Problem* problem = Opt_ProblemDefine(state,"../src/laplacian.opt", "solverGaussNewtonGPU");`

The supported solver are `gaussNewtonGPU` and `LMGPU`.  If you haven't changed that, it may be the problem.

**Comment by ricshaw** [comment]
I have also changed that to gaussNewtonGPU.

**Comment by ricshaw** [comment]
Can anyone provide a working version of the Laplacian image smoothing code?

**Comment by Mx7f** [comment]
@mvito, did the above code work when you changed "solverGaussNewtonGPU" to "gaussNewtonGPU" and doeuble-precision to 0?

**Comment by Mx7f** [comment]
I've added a minimal test case that uses Opt to laplacian smooth white noise and output the result (see tests/minimal). It depends only on Opt and CUDA and uses the public domain stb_image_write library for image saving.
