### ISSUE TITLE
Why is the position argument needed explicitly in Opt?

### ISSUE THREAD

**Issue by mihaibujanca** [niessner/Opt#93]
I might be missing something, but why is the "position" argument needed? It feels like for whatever happens under the hood, it could be kept there without requiring the user to hand write the next increment whenever adding a new variable.

Consider the following example:
``` 
-- Opt
local W = Dim("W",0)
local H =  Dim("H",1)
```

``` 
//c++
unsigned int width = 640;
unsigned int height = 480;
m_dims = {width, height}
addOptSolvers(m_dims, "solver.t");
```

This seems to be working fine, so I'm assuming that only the position is used here, thus making the name redundant. Conversely, when having named parameters, the position argument seems to be redundant.

I guess this is a curiosity of mine rather than a complaint / actual issue, but is it just easier to do it like that in Terra or are there some considerations I might not be aware of?

Thanks

**Comment by Mx7f** [comment]
Indices were easier to work with during development than named parameters, automagical indexing is easy to screw up, and naming parameters makes debugging easier. 

We might move to named parameter passing in the future and then get rid of explicit indices.

**Comment by mihaibujanca** [comment]
Thanks, that makes sense!
