### ISSUE TITLE
Cannot find the code to generate input binary files in the example: shape from shading

### ISSUE THREAD

**Issue by rongduo** [niessner/Opt#96]
In the example of shape from shading, the input file is given in the form of binary files, but I did not find the code which can generate such binary files from images. I made some attempts, but the files generated by myself are not corresponding with yours.

**Comment by Mx7f** [comment]
The binary files are a very simple binary ad-hoc format. You can see read/write code here: https://github.com/niessner/Opt/blob/master/examples/shape_from_shading/src/SimpleBuffer.cpp

They are essentially laid out like:

struct SimpleBufferBinaryLayout {
int width;
int height;
int channelCount;
int type; // 0 for float, 1 for uchar
uchar data*; // sizeof(width*height*channel*byteCountOfType(type))
}


That being said, the example code is meant to demonstrate the capabilities of Opt, they are not designed with a mind for immediately working in an external pipeline.
